### ISSUE TITLE
[Feature] Dark variant?

### ISSUE THREAD

**Issue by jacksongoode** [leodr/ulauncher-theme-libadwaita#1]
Just a thought!

**Comment by leodr** [comment]
I mostly use light mode so I probably won’t implement this, but you can have a go at it by forking the repo.

Basically just have to replace the colors in `theme.css`, you can grab them with GTK Inspector from any libadwaita application.

https://wiki.gnome.org/Projects/GTK/Inspector

**Comment by Nakamerica** [comment]
@jacksongoode https://github.com/lighttigerXIV/ulauncher-adwaita-gtk4.git
