### ISSUE TITLE
dark theme

### ISSUE THREAD

**Issue by kareemkasem** [leodr/ulauncher-theme-libadwaita#2]
Hi, leodr. Great work on the theme. I truly love it. I was wondering if you could also make it in dark theme. Thanks.

**Comment by leodr** [comment]
Thanks! I am currently not using Ulauncher anywhere, so won't work on this. I'll leave this open if I come come back to using it.

**Comment by kareemkasem** [comment]
I created a dark fork of your theme [here](https://github.com/kareemkasem/ulauncher-theme-libadwaita-dark) :)

**Comment by leodr** [comment]
> I created a dark fork of your theme [here](https://github.com/kareemkasem/ulauncher-theme-libadwaita-dark) :)

Looks great, I’ll add a link to the Readme :)
